const quotes = [
    "Không có việc gì khó nếu chúng ta cùng nhau chia sẻ và hỗ trợ nhau. 🤝",
    "Sự thành công không đến từ sự hoàn hảo, mà từ sự kiên trì, nỗ lực và học hỏi từ thất bại. 💪",
    "Hãy nhớ rằng mục tiêu lớn nhất chỉ có thể đạt được bằng cách bắt đầu từ những bước nhỏ nhất. 🏁",
    "Sức mạnh của đồng đội không phải là sức mạnh của cá nhân, mà là sức mạnh của sự đoàn kết. 🤗",
    "Thất bại chỉ xảy ra khi bạn từ bỏ. Hãy luôn cố gắng và không bao giờ từ bỏ. 🔥",
    "Hãy lắng nghe ý kiến của mọi người, vì mỗi ý kiến đều quan trọng và có thể giúp chúng ta tiến xa hơn. 👂",
    "Đội làm việc mạnh mẽ không phải là nơi các cá nhân xuất sắc tồn tại, mà là nơi mà mỗi thành viên được hỗ trợ và động viên để phát triển. 🌱",
    "Thành công không phải là chìa khóa của hạnh phúc, mà hạnh phúc là chìa khóa của thành công. Nếu bạn yêu những gì bạn đang làm, bạn sẽ thành công. ❤️",
    "Hãy nhớ rằng thách thức không phải là một vấn đề, mà là cơ hội để chúng ta vượt qua bản thân và phát triển. 🚀",
    "Sức mạnh của đồng đội nằm ở việc hỗ trợ và tin tưởng lẫn nhau. 👥",
    "Hãy chấp nhận thất bại nhưng đừng bao giờ từ bỏ. Hãy học từ những sai lầm và tiến lên với niềm tin. 🏆",
    "Mỗi bước tiến là một cơ hội học hỏi mới. Đừng bao giờ sợ thất bại. 📚",
    "Không có con đường nào dẫn đến thành công mà không có nỗ lực và công sức. 🛠️",
    "Hãy cùng nhau xây dựng một môi trường làm việc tích cực và động viên nhau đạt được mục tiêu. 🌟",
    "Mỗi ngày là một cơ hội mới để trở nên tốt hơn. Hãy tận dụng ngày hôm nay để tiến xa hơn ngày mai. 🌅",
    "Thành công không đến từ sự ngẫu nhiên, mà từ sự kiên trì và đam mê. 🔑",
    "Hãy nhớ rằng mỗi khó khăn đều là một cơ hội để chúng ta phát triển và trở nên mạnh mẽ hơn. 💥",
    "Hãy tôn trọng và đánh giá cao những nỗ lực của mỗi thành viên trong đội. Sức mạnh của đồng đội nằm ở sự đa dạng và sự kết hợp của tất cả. 🏅",
    "Sự đoàn kết và sự chia sẻ là chìa khóa để chúng ta vượt qua mọi thách thức. 🔗",
    "Hãy hướng về phía trước với lòng quả cảm và niềm tin. Đường đến thành công không bao giờ là một con đường dễ dàng, nhưng nó chắc chắn đáng giá. 💫",
    "Mỗi thử thách là một bài học quý giá để chúng ta tiến gần hơn tới mục tiêu. 🏔️",
    "Chỉ có sự kiên trì và nỗ lực không ngừng mới giúp chúng ta đạt được những điều lớn lao. 🔄",
    "Thành công không phải là đích đến, mà là hành trình mà chúng ta trải qua. 🛤️",
    "Đừng để thất bại làm bạn nản chí. Thay vào đó, hãy để nó là động lực để bạn cố gắng hơn. 🏃‍♂️",
    "Hãy đặt mục tiêu cao và không ngừng phấn đấu để đạt được chúng. 🎯",
    "Sự sáng tạo và đổi mới là chìa khóa để thành công trong một thế giới thay đổi nhanh chóng. 💡",
    "Hãy không ngừng học hỏi và phát triển, vì chỉ có kiến thức mới giúp chúng ta vươn xa. 🎓",
    "Không có sự nỗ lực nào là vô nghĩa. Mỗi bước đi đều giúp chúng ta tiến gần hơn đến thành công. 🦸‍♀️",
    "Thành công không phải là do may mắn, mà là kết quả của sự chuẩn bị, sự nỗ lực và cơ hội. 🔍",
    "Đôi khi, những điều tuyệt vời nhất trong cuộc sống đến từ những bước đi không ngờ tới. 🌠",
    "Hãy luôn nhớ rằng, khi bạn làm việc chăm chỉ và có niềm tin, không có gì là không thể. 💥",
    "Không có gì là không thể nếu bạn kiên trì và quyết tâm theo đuổi mục tiêu của mình. 🌈",
    "Mỗi ngày là một cơ hội mới để thay đổi, để trưởng thành và để thành công. ⏳"
];

module.exports = { quotes };